export const CONSTANTS = {
  CASH_ACCOUNT: "Cash Account",
  NA: "NA",
  CASH: "CASH",
  ADJUSTMENT: "ADJUSTMENT",
  OTHERS: "Others",
  HDPE_BAGS: "HDPE Bags",
  IN: "IN",
  OUT: "OUT",
  CREDIT: "Credit",
  DEBIT: "Debit",
  WHOLESALE_DEALER: "Wholesale dealer",
  RETAIL_DEALER: "Retail dealer",
  INDUSTRIAL_DEALER: "Industrial dealer",
};
